title: Vamo
baseurl: "/vamo"
url: "https://ararog.github.io"

theme: jekyll-theme-cayman

markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      toc: true
      toc_sticky: true
      sidebar:
        nav: "navigation"
